# Generated by Django 4.1.7 on 2023-03-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('account', models.CharField(max_length=30)),
                ('passWord', models.CharField(max_length=40)),
                ('eMail', models.EmailField(max_length=254)),
            ],
        ),
    ]
