# Generated by Django 4.1.7 on 2023-03-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='createTime',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
